import { marker as localized$ } from '@colsen1991/ngx-translate-extract-marker';

export const colour = [
  { name: 'Black', code: 'black' },
  { name: 'Blue', code: 'blue' },
  { name: 'Brown', code: 'brown' },
  { name: 'Coloured/jazz', code: 'coloured_jazz' },
  { name: 'Green', code: 'green' },
  { name: 'Grey', code: 'grey' },
  { name: 'Natural', code: 'natural' },
  { name: 'Red', code: 'red' },
  { name: 'White', code: 'white' },
];

export const finishing = [
  { name: 'Baled', code: 'baled' },
  { name: 'Blocks', code: 'blocks' },
  { name: 'Flakes', code: 'flakes' },
  { name: 'Lumps', code: 'lumps' },
  { name: 'Masterbatch', code: 'masterbatch' },
  { name: 'Pieces', code: 'pieces' },
  { name: 'Powder', code: 'powder' },
  { name: 'Regrind', code: 'regrind' },
  { name: 'Resin', code: 'resin' },
  { name: 'Rolls', code: 'rolls' },
  { name: 'Sheets', code: 'sheets' },
  { name: 'Shred', code: 'shred' },
];

export const packing = [
  { name: 'Bags', code: 'bags' },
  { name: 'Bales', code: 'bales' },
  { name: 'Boxes', code: 'boxes' },
  { name: 'Bulk Bags', code: 'bulk_bags' },
  { name: 'Loose', code: 'loose' },
  { name: 'Octabins/\u200BGaylords', code: 'octabins_gaylords' },
  { name: 'Pallets', code: 'pallets' },
];

export const plasticForm = [
  { name: 'Airbags', code: 'airbags' },
  { name: 'Bags', code: 'bags' },
  { name: 'Bins', code: 'bins' },
  { name: 'Blister', code: 'blister' },
  { name: 'Bottles', code: 'bottles' },
  { name: 'Buckets', code: 'buckets' },
  { name: 'Bumpers', code: 'bumpers' },
  { name: 'Cable/s', code: 'cables' },
  { name: 'Cans', code: 'cans' },
  { name: 'Caps', code: 'caps' },
  { name: 'Casings', code: 'casings' },
  { name: 'Cores', code: 'cores' },
  { name: 'Corex', code: 'corex' },
  { name: 'Crates', code: 'crates' },
  { name: 'Cups', code: 'cups' },
  { name: 'Discs', code: 'discs' },
  { name: 'Door Skins', code: 'door_skins' },
  { name: 'Drip Tape', code: 'drip_tape' },
  { name: 'Film', code: 'film' },
  { name: 'Filters', code: 'filters' },
  { name: 'Fines', code: 'fines' },
  { name: 'Fishing Line', code: 'fishing_line' },
  { name: 'Hangers', code: 'hangers' },
  { name: 'Keyboard', code: 'keyboard' },
  { name: 'Modem', code: 'modem' },
  { name: 'Moulds', code: 'moulds' },
  { name: 'Nets', code: 'nets' },
  { name: 'Pipes', code: 'pipes' },
  { name: 'Pots', code: 'pots' },
  { name: 'Preforms', code: 'preforms' },
  { name: 'Printer', code: 'printer' },
  { name: 'Profiles', code: 'profiles' },
  { name: 'Reels', code: 'reels' },
  { name: 'Rigid', code: 'rigid' },
  { name: 'Runners', code: 'runners' },
  { name: 'Skeletons', code: 'skeletons' },
  { name: 'Soft', code: 'soft' },
  { name: 'Sprues', code: 'sprues' },
  { name: 'Strapping', code: 'strapping' },
  { name: 'String', code: 'string' },
  { name: 'Tool', code: 'tool' },
  { name: 'Trays', code: 'trays' },
  { name: 'Tubes', code: 'tubes' },
  { name: 'Vacuum', code: 'vacuum' },
];

export const plasticGrading = [
  { name: '6', code: '6' },
  { name: '12', code: '12' },
  { name: '46', code: '46' },
  { name: '66', code: '66' },
  { name: '100', code: '100' },
  { name: '612', code: '612' },
  { name: '*1-7', code: '1-7' },
  { name: '*3-7', code: '3-7' },
  { name: 'Jun-66', code: 'jun_66' },
  { name: '50/50', code: '50_50' },
  { name: '60/40', code: '60_40' },
  { name: '70/30', code: '70_30' },
  { name: '75/25', code: '75_25' },
  { name: '80/20', code: '80_20' },
  { name: '85/15', code: '85_15' },
  { name: '90/10', code: '90_10' },
  { name: '95/5', code: '95_5' },
  { name: '98/2', code: '98_2' },
  { name: '99/1', code: '99_1' },
  { name: 'A Grade', code: 'a_grade' },
  { name: 'Agricultural', code: 'agricultural' },
  { name: 'Aluminium', code: 'aluminium' },
  { name: 'Automotive', code: 'automotive' },
  { name: 'B Grade', code: 'b_grade' },
  { name: 'C Grade', code: 'c_grade' },
  { name: 'CD', code: 'cd' },
  { name: 'CD/DVD', code: 'cd_dvd' },
  { name: 'Coated', code: 'coated' },
  { name: 'Computer', code: 'computer' },
  { name: 'Construction', code: 'construction' },
  { name: 'DVD', code: 'dvd' },
  { name: 'Electrical', code: 'electrical' },
  { name: 'Fish Box', code: 'fish_box' },
  { name: 'Floor Sweeps', code: 'floor_sweeps' },
  { name: 'Fridge', code: 'fridge' },
  { name: 'G', code: 'g' },
  { name: 'GF', code: 'gf' },
  { name: 'GF10', code: 'gf10' },
  { name: 'GF15', code: 'gf15' },
  { name: 'GF20', code: 'gf20' },
  { name: 'GF25', code: 'gf25' },
  { name: 'GF30', code: 'gf30' },
  { name: 'GF35', code: 'gf35' },
  { name: 'GF40', code: 'gf40' },
  { name: 'GF50', code: 'gf50' },
  { name: 'LCD', code: 'lcd' },
  { name: 'Metalised', code: 'metalised' },
  { name: 'Mixed', code: 'mixed' },
  { name: 'Non-Woven', code: 'non_woven' },
  { name: 'Offcuts', code: 'offcuts' },
  { name: 'Printed', code: 'printed' },
  { name: 'Production Waste', code: 'production_waste' },
  { name: 'Supermarket', code: 'supermarket' },
  { name: 'Technical', code: 'technical' },
  { name: 'TV', code: 'tv' },
  { name: 'Tyvek', code: 'tyvek' },
  { name: 'Uncoated', code: 'uncoated' },
  { name: 'Walmart', code: 'walmart' },
  { name: 'Washing Machine', code: 'washing_machine' },
  { name: 'Wet', code: 'wet' },
  { name: 'Woven', code: 'woven' },
  { name: 'Laminates', code: 'laminates' },
];

export const fibreGrading = [
  { name: 'High', code: 'high' },
  { name: 'Kraft', code: 'kraft' },
  { name: 'Medium', code: 'medium' },
  { name: 'Ordinary', code: 'ordinary' },
  { name: 'Special', code: 'special' },
];

export const materialTypes = [
  {
    name: 'Plastic',
    code: 'plastic',
    materials: [
      { name: 'ABS', code: 'abs' },
      { name: 'BOPP', code: 'bopp' },
      { name: 'EPS', code: 'eps' },
      { name: 'EVA', code: 'eva' },
      { name: 'EVOH', code: 'evoh' },
      { name: 'HDPE', code: 'hdpe' },
      { name: 'HDPE/PP', code: 'hdpe_pp' },
      { name: 'K-Resin', code: 'k_resin' },
      { name: 'LDPE', code: 'ldpe' },
      { name: 'LLDPE', code: 'lldpe' },
      { name: 'MDPE', code: 'mdpe' },
      { name: 'PA', code: 'pa' },
      { name: 'PBT', code: 'pbt' },
      { name: 'PC', code: 'pc' },
      { name: 'PC/ABS', code: 'pc_abs' },
      { name: 'PE', code: 'pe' },
      { name: 'PE/PA', code: 'pe_pa' },
      { name: 'PE/PET', code: 'pe_pet' },
      { name: 'PE/PP', code: 'pe_pp' },
      { name: 'PET', code: 'pet' },
      { name: 'PET/PVC', code: 'pet_pvc' },
      { name: 'PMMA', code: 'pmma' },
      { name: 'POM', code: 'pom' },
      { name: 'PP', code: 'pp' },
      { name: 'PP/PET', code: 'pp_pet' },
      { name: 'PP/PS', code: 'pp_ps' },
      { name: 'PS', code: 'ps' },
      { name: 'PVC', code: 'pvc' },
      { name: 'SAN', code: 'san' },
      { name: 'Silicone', code: 'silicone' },
      { name: 'TPO', code: 'tpo' },
      { name: 'TPU', code: 'tpu' },
      { name: 'Black Casings', code: 'black_casings' },
      { name: 'Crème Casings', code: 'creme_casings' },
      { name: 'Fridge', code: 'fridge' },
      { name: 'Mixed Casings', code: 'mixed_casings' },
      { name: 'Mixed WEEE', code: 'mixed_weee' },
      { name: 'Bumpers', code: 'bumpers' },
      { name: 'Mixed Bottles', code: 'mixed_bottles' },
      { name: 'Mixed Film', code: 'mixed_film' },
      { name: 'Mixed Hangers', code: 'mixed_hangers' },
      { name: 'Mixed Plastic', code: 'mixed_plastic' },
      { name: 'Mixed Rigids', code: 'mixed_rigids' },
      { name: 'Mixed Strapping', code: 'mixed_strapping' },
    ],
    form: plasticForm,
    grading: plasticGrading,
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'EFW',
    code: 'efw',
    materials: [],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Metals',
    code: 'metal',
    materials: [
      { name: 'FF', code: 'ff' },
      { name: 'N2', code: 'n2' },
      { name: 'OA', code: 'oa' },
      { name: 'OSB', code: 'osb' },
      { name: 'OSOA', code: 'osoa' },
      { name: 'TCANS', code: 'tcans' },
      { name: 'ACANS', code: 'acans' },
      { name: 'Aluminium', code: 'aluminium' },
      { name: 'Brass', code: 'brass' },
      { name: 'Braziery Copper', code: 'braziery_copper' },
      { name: 'Copper', code: 'copper' },
      { name: 'Stainless Steel 304', code: 'stainless_steel_304' },
      { name: 'Stainless Steel 316', code: 'stainless_steel_316' },
    ],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Fibre',
    code: 'fibre',
    materials: [
      { name: 'Medium printed multi printing', code: 'medium_printed_multi_printing' },
      { name: 'Mixed white heavily printed multiply board', code: 'mixed_white_heavily_printed_multiply_board' },
      { name: 'Multi printing', code: 'multi_printing' },
      { name: 'Special wood free binders', code: 'special_wood_free_binders' },
      { name: 'Unprinted bleached sulphate board', code: 'unprinted_bleached_sulphate_board' },
      { name: 'Unprinted tissue coloured in the mass', code: 'unprinted_tissue_coloured_in_the_mass' },
      { name: 'White coated woodfree paper', code: 'white_coated_woodfree_paper' },
      { name: 'White envelope cuttings', code: 'white_envelope_cuttings' },
      { name: 'White heavily printed multiply board', code: 'white_heavily_printed_multiply_board' },
      { name: 'White lightly printed multi-ply board', code: 'white_lightly_printed_multi_ply_board' },
      {
        name: 'White mechanical pulp-based coated and uncoated paper',
        code: 'white_mechanical_pulp_based_coated_and_uncoated_paper',
      },
      {
        name: 'White mechanical pulp-based paper containing coated paper',
        code: 'white_mechanical_pulp_based_paper_containing_coated_paper',
      },
      { name: 'White shavings', code: 'white_shavings' },
      { name: 'White unprinted multi-ply board', code: 'white_unprinted_multi_ply_board' },
      { name: 'White unprinted tissue', code: 'white_unprinted_tissue' },
      { name: 'White wood free uncoated shavings', code: 'white_wood_free_uncoated_shavings' },
      { name: 'White woodfree letters', code: 'white_woodfree_letters' },
      { name: 'White woodfree letters unprinted', code: 'white_woodfree_letters_unprinted' },
      { name: 'White woodfree papers', code: 'white_woodfree_papers' },
      { name: 'White woodfree shavings', code: 'white_woodfree_shavings' },
      { name: 'Woodfree binders', code: 'woodfree_binders' },
      { name: 'New shavings of corrugated board', code: 'new_shavings_of_corrugated_board' },
      { name: 'Unused corrugated kraft', code: 'unused_corrugated_kraft' },
      { name: 'Unused corrugated material', code: 'unused_corrugated_material' },
      { name: 'Used corrugated kraft 1', code: 'used_corrugated_kraft_1' },
      { name: 'Used kraft', code: 'used_kraft' },
      { name: 'Colored log end tissue', code: 'coloured_log_end_tissue' },
      { name: 'Heavily printed white shavings', code: 'heavily_printed_white_shavings' },
      { name: 'Heavily printed white shavings without glue', code: 'heavily_printed_white_shavings_without_glue' },
      { name: 'Lightly printed white shavings', code: 'lightly_printed_white_shavings' },
      { name: 'Lightly printed white shavings without glue', code: 'lightly_printed_white_shavings_without_glue' },
      { name: 'Multigrade', code: 'multigrade' },
      { name: 'Newspapers', code: 'newspapers' },
      { name: 'Ordinary sorted colored letters', code: 'ordinary_sorted_colored_letters' },
      { name: 'Ordinary sorted office paper', code: 'ordinary_sorted_office_paper' },
      { name: 'Sorted coloured letters', code: 'sorted_coloured_letters' },
      { name: 'Unsold newspapers', code: 'unsold_newspapers' },
      { name: 'Unsold newspapers not intended for deinking', code: 'unsold_newspapers_not_intended_for_deinking' },
      { name: 'White log end tissue', code: 'white_log_end_tissue' },
      { name: 'White mechanical pulp-based bookquire', code: 'white_mechanical_pulp_based_bookquire' },
      { name: 'White woodfree bookquire', code: 'white_woodfree_bookquire' },
      { name: 'Blister pack', code: 'blister_pack' },
      { name: 'Carbonless copy paper (Ncr)', code: 'carbonless_copy_paper' },
      { name: 'Cores', code: 'cores' },
      { name: 'Dry labels', code: 'dry_labels' },
      { name: 'Labels with base layer', code: 'labels_with_base_layer' },
      { name: 'Mixed envelopes', code: 'mixed_envelopes' },
      { name: 'Mixed packaging', code: 'mixed_packaging' },
      { name: 'Mixed papers', code: 'mixed_papers' },
      {
        name: 'Printed white and coloured wetstrength woodfree papers',
        code: 'printed_white_and_colored_wet_strength_woodfree_papers',
      },
      { name: 'Printed White Envelope', code: 'printed_white_envelope' },
      { name: 'Printed White Wet-Strength Woodfree Papers', code: 'printed_white_wet_strength_woodfree_papers' },
      {
        name: 'Unprinted White And Colored Wet-Strength Papers',
        code: 'unprinted_white_and_colored_wet_strength_papers',
      },
      {
        name: 'Unprinted White Wet-Strength Woodfree Papers',
        code: 'unprinted_white_wet_strength_woodfree_papers_unprinted_white_wets',
      },
      { name: 'Unused Kraft Sacks', code: 'unused_kraft_sacks' },
      {
        name: 'Unused Kraft Sacks With Plastic Layer Papers And Poly Liners',
        code: 'unused_kraft_sacks_with_plastic_layer_papers_and_poly_liners',
      },
      { name: 'Unused Liquid Packaging Board', code: 'unused_liquid_packaging_board' },
      { name: 'Unused Paper Cups And Other Tableware', code: 'unused_paper_cups_and_other_tableware' },
      { name: 'Used Kraft Sacks', code: 'used_kraft_sacks' },
      { name: 'Used Kraft Sacks With Plastic Layer Papers', code: 'used_kraft_sacks_with_plastic_layer_papers' },
      { name: 'Used Liquid Packaging Board', code: 'used_liquid_packaging_board' },
      { name: 'Used Paper Cups And Other Used Tableware', code: 'used_paper_cups_and_other_used_tableware' },
      { name: 'Wet Labels', code: 'wet_labels' },
      { name: 'Corrugated board', code: 'corrugated_board' },
      { name: 'Corrugated paper and board', code: 'corrugated_paper_and_board' },
      { name: 'Corrugated paper and board packaging', code: 'corrugated_paper_and_board_packaging' },
      { name: 'Grey board', code: 'grey_board' },
      { name: 'Magazines', code: 'magazines' },
      { name: 'Magazines with product samples', code: 'magazines_with_product_samples' },
      { name: 'Magazines without glue', code: 'magazines_without_glue' },
      { name: 'Mixed magazines and newspapers', code: 'mixed_magazines_and_newspapers' },
      { name: 'Mixed newspapers & magazines 1', code: 'mixed_newspapers_and_magazines_1' },
      { name: 'Mixed papers and boards (sorted)', code: 'mixed_papers_and_boards_sorted' },
      { name: 'Newspapers and magazines', code: 'newspapers_and_magazines' },
      { name: 'Ordinary corrugated board', code: 'ordinary_corrugated_board' },
      { name: 'Ordinary corrugated paper and board', code: 'ordinary_corrugated_paper_and_board' },
      { name: 'Sorted graphic paper for deinking', code: 'sorted_graphic_paper_for_deinking' },
    ],
    form: [],
    grading: fibreGrading,
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Rubber',
    code: 'rubber',
    materials: [
      { code: 'natural_rubber', name: 'Natural rubber' },
      { code: 'chloroprene_rubber_CR', name: 'Chloroprene Rubber (CR)' },
      { code: 'elastomers', name: 'Elastomers' },
      { code: 'ethylene_propylene_diene_monomer_epdm', name: 'Ethylene-Propylene-Diene Monomer (EPDM)' },
      { code: 'latex_products', name: 'Latex Products' },
      { code: 'nitrile_rubber_nbr', name: 'Nitrile Rubber (NBR)' },
      { code: 'polybutadiene_rubber_BR', name: 'Polybutadiene Rubber (BR)' },
      { code: 'polyurethane_rubber_PU', name: 'Polyurethane Rubber (PU)' },
      { code: 'recycled_rubber_products', name: 'Recycled Rubber Products' },
      { code: 'rubber_compounds', name: 'Rubber Compounds' },
      { code: 'rubber_conveyor_belts', name: 'Rubber Conveyor Belts' },
      { code: 'rubber_footwear', name: 'Rubber Footwear' },
      { code: 'rubber_hoses_and_tubing', name: 'Rubber Hoses and Tubing' },
      { code: 'rubber_manufacturing_waste', name: 'Rubber Manufacturing Waste' },
      { code: 'rubber_playground_surfaces', name: 'Rubber Playground Surfaces' },
      { code: 'rubber_seals_and_gaskets', name: 'Rubber Seals and Gaskets' },
      { code: 'styrene_butadiene_rubber', name: 'Styrene-Butadiene Rubber (SBR)' },
    ],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
];

export const mapCodeToMaterialForm = plasticForm.reduce(
  (memo, item) => {
    memo[item.code] = localized$(item.name);

    return memo;
  },
  {} as Record<string, string>,
);

export const mapCodeToMaterialFinishing = finishing.reduce(
  (memo, item) => {
    memo[item.code] = localized$(item.name);

    return memo;
  },
  {} as Record<string, string>,
);

export const mapCodeToMaterialItem = materialTypes.reduce(
  (memo, item) => {
    item.materials.forEach((material) => {
      memo[material.code] = localized$(material.name);
    });

    return memo;
  },
  {} as Record<string, string>,
);

export const mapCodeToMaterialGrading = fibreGrading.reduce(
  (memo, item) => {
    memo[item.code] = localized$(item.name);

    return memo;
  },
  {} as Record<string, string>,
);

export const mapCodeToPackaging = packing.reduce(
  (memo, item) => {
    memo[item.code] = localized$(item.name);
    return memo;
  },
  {} as Record<string, string>,
);
