export enum NotificationType {
    ACCOUNT_VERIFIED = 'account_verified',
    ACCOUNT_REJECTED = 'account_rejected',
    PROFILE_UPDATED = 'profile_updated',
    NOTIFICATIONS_ENABLED = 'notifications_enabled',
    DOCUMENT_EXPIRY = 'document_expiry',
    LISTING_ADDED = 'listing_added',
    LISTING_APPROVED = 'listing_approved',
    LISTING_REJECTED = 'listing_rejected',
    LISTING_MORE_INFORMATION_REQUIRED = 'listing_more_information_required',
    LISTING_RENEWED = 'listing_renewed',
    LISTING_EXPIRY_WARNING = 'listing_expiry_warning',
    OFFER_APPROVED = 'offer_approved',
    OFFER_STATUS_UPDATED = 'offer_status_updated',
    NEW_HAULAGE_OPPORTUNITY = 'new_haulage_opportunity',
    HAULAGE_OFFER_APPROVED = 'haulage_offer_approved',
    HAULAGE_OFFER_REJECTED = 'haulage_offer_rejected',
    HAULAGE_OFFER_REQUEST_INFORMATION = 'haulage_offer_request_information',

    COMPANY_USER_REQUEST_JOIN = 'company_user_request_join',
    COMPANY_USER_ACCEPTED_INVITE = 'company_user_accepted_invite',
    COMPANY_USER_REJECTED_REQUEST_JOIN = 'company_user_rejected_request_join',
    COMPANY_USER_ROLE_CHANGED = 'company_user_role_changed',
    COMPANY_USER_UNLINKED_FROM_COMPANY = 'company_user_unlinked_from_company',
}
