import { addLanguagePrefix } from '../utils/language.utils';

export const ROUTES = {
  login: 'login',
  buy: 'buy',
  wanted: 'wanted',
  saleListings: 'my-account/my-current-listings',
  wantedListings: 'my-account/my-wanted-listings',
  accountPendingResult: 'complete-your-account',
  sites: 'my-sites',
  sell: 'sell',
  createWantedListing: 'wanted-listing',
  admin: 'admin',
  haulier: 'haulier-dashboard',
  availableLoads: 'haulier-dashboard',
  makeOffer: 'haulier-submit-offer',
  haulierOffer: 'haulier-offer',
  haulierProfile: 'haulier-profile',
  settings: 'settings',
  logout: 'logout',
  myOffersSelling: 'my-account/my-offers-selling',
  myOffersBuying: 'my-account/my-offers-buying',
  myOffersBuyingDetail: 'my-account/my-buying-offers-details',
  offerDetail: 'offer-detail',
  listingOfferDetail: 'wt_waste_listing',
  wantedListingOfferDetail: 'wt_wanted_listing',
  liveActiveTable: 'live-activity',
  commercialManagement: 'commercial-management',
  auditTrail: 'audit-trail',
  userManagement: 'user-management',
  companyMembers: 'company-members',
  adminDetail: 'admin-detail',
  adminSaleListingDetail: 'admin/listing',
  adminWantedListingDetail: 'admin/wanted-listing',
  adminBuyerActivityDetail: 'admin/buyer-activity',
  adminMemberDetail: 'admin/member',
  adminHaulageBid: 'admin/haulage-bid',
  adminMakeOffer: 'admin/make-haulier-offer',
  landingPage: 'landing-page',
  requestSuccessHaulier: 'request-success-haulier',
  requestSuccessTrader: 'request-success-trader',
};

const ROUTES_BASE = {
  login: '/login',
  buy: '/buy',
  wanted: '/wanted',
  saleListings: '/my-account/my-current-listings',
  wantedListings: '/my-account/my-wanted-listings',
  accountPendingResult: '/complete-your-account',
  sites: '/my-sites',
  sell: '/sell',
  createWantedListing: '/wanted-listing',
  admin: '/admin',
  haulier: '/haulier-dashboard',
  availableLoads: '/haulier-dashboard',
  makeOffer: '/haulier-submit-offer',
  currentOffers: '/haulier-offer',
  haulierProfile: '/haulier-profile',
  settings: '/settings',
  logout: '/logout',
  myOffersSelling: '/my-account/my-offers-selling',
  myOffersBuying: '/my-account/my-offers-buying',
  myOffersBuyingDetail: '/my-account/my-buying-offers-details',
  offerDetail: '/offer-detail',
  companyMembers: '/company-members',
  listingOfferDetail: '/wt_waste_listing',
  wantedListingOfferDetail: '/wt_wanted_listing',
  liveActiveTable: '/live-activity',
  commercialManagement: '/commercial-management',
  auditTrail: '/audit-trail',
  userManagement: '/user-management',
  adminDetail: '/admin-detail',
  adminSaleListingDetail: '/admin/listing',
  adminBuyerActivityDetail: '/admin/buyer-activity',
  adminWantedListingDetail: '/admin/wanted-listing',
  adminMemberDetail: '/admin/member',
  adminHaulageBid: '/admin/haulage-bid',
  adminMakeOffer: '/admin/make-haulier-offer',
  landingPage: '/landing-page',
  requestSuccessHaulier: '/request-success-haulier',
  requestSuccessTrader: '/request-success-trader',
};

// Create a Proxy to automatically add language prefix to all routes
export const ROUTES_WITH_SLASH = new Proxy(ROUTES_BASE, {
  get(target: any, prop: string) {
    const route = target[prop];
    if (typeof route === 'string') {
      return addLanguagePrefix(route);
    }
    return route;
  },
}) as typeof ROUTES_BASE;
