export const UK_ISO_CODE = 'GB';

export const EU_ISO_CODES = [
    'AT', // Austria
    'BE', // Belgium
    'BG', // Bulgaria
    'HR', // Croatia
    'CY', // Cyprus
    'CZ', // Czech Republic / Czechia
    'DK', // Denmark
    'EE', // Estonia
    'FI', // Finland
    'FR', // France
    'DE', // Germany
    'GR', // Greece
    'HU', // Hungary
    'IE', // Ireland
    'IT', // Italy
    'LV', // Latvia
    'LT', // Lithuania
    'LU', // Luxembourg
    'MT', // Malta
    'NL', // Netherlands
    'PL', // Poland
    'PT', // Portugal
    'RO', // Romania
    'SK', // Slovakia
    'SI', // Slovenia
    'ES', // Spain
    'SE', // Sweden
];

export const REST_ISO_CODES = [
    'AD',
    'AE',
    'AF',
    'AG',
    'AI',
    'AL',
    'AM',
    'AN',
    'AO',
    'AQ',
    'AR',
    'AS',
    'AU',
    'AW',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BF',
    'BH',
    'BI',
    'BJ',
    'BL',
    'BM',
    'BN',
    'BO',
    'BR',
    'BS',
    'BT',
    'BW',
    'BY',
    'BZ',
    'CA',
    'CC',
    'CD',
    'CF',
    'CG',
    'CH',
    'CI',
    'CK',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CU',
    'CV',
    'CW',
    'CX',
    'DJ',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EG',
    'EH',
    'ER',
    'ET',
    'FJ',
    'FK',
    'FM',
    'FO',
    'GA',
    'GD',
    'GE',
    'GH',
    'GI',
    'GL',
    'GM',
    'GN',
    'GQ',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HN',
    'HT',
    'ID',
    'IL',
    'IN',
    'IO',
    'IQ',
    'IR',
    'IS',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KP',
    'KR',
    'KW',
    'KY',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MF',
    'MG',
    'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MR',
    'MS',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NG',
    'NI',
    'NO',
    'NP',
    'NR',
    'NU',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PF',
    'PG',
    'PH',
    'PK',
    'PM',
    'PN',
    'PR',
    'PS',
    'PW',
    'PY',
    'QA',
    'RE',
    'RS',
    'RU',
    'RW',
    'SA',
    'SB',
    'SC',
    'SD',
    'SG',
    'SH',
    'SJ',
    'SL',
    'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    'ST',
    'SV',
    'SX',
    'SY',
    'SZ',
    'TC',
    'TD',
    'TG',
    'TH',
    'TJ',
    'TK',
    'TL',
    'TM',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'US',
    'UY',
    'UZ',
    'VA',
    'VC',
    'VE',
    'VG',
    'VI',
    'VN',
    'VU',
    'WF',
    'WS',
    'XK',
    'YE',
    'YT',
    'ZA',
    'ZM',
    'ZW',
];

export const COUNTRIES_LIST = [
    {
        isoCode: 'AD',
        name: 'Andorra',
        flagClass: 'fi-ad',
        inputMasking: '999 999',
        code: '+376 ',
        normalizedCode: '376',
    },
    {
        isoCode: 'AE',
        name: 'United Arab Emirates',
        flagClass: 'fi-ae',
        inputMasking: '999 999 9999',
        code: '+971 ',
        normalizedCode: '971',
    },
    {
        isoCode: 'AF',
        name: 'Afghanistan',
        flagClass: 'fi-af',
        inputMasking: '999 999 9999',
        code: '+93 ',
        normalizedCode: '93',
    },
    {
        isoCode: 'AG',
        name: 'Antigua and Barbuda',
        flagClass: 'fi-ag',
        inputMasking: '999-9999',
        code: '+1 (268) ',
        normalizedCode: '1268',
    },
    {
        isoCode: 'AI',
        name: 'Anguilla',
        flagClass: 'fi-ai',
        inputMasking: '999-9999',
        code: '+1 (264) ',
        normalizedCode: '1264',
    },
    {
        isoCode: 'AL',
        name: 'Albania',
        flagClass: 'fi-al',
        inputMasking: '999 999 9999',
        code: '+355 ',
        normalizedCode: '355',
    },
    {
        isoCode: 'AM',
        name: 'Armenia',
        flagClass: 'fi-am',
        inputMasking: '999 999999',
        code: '+374 ',
        normalizedCode: '374',
    },
    {
        isoCode: 'AN',
        name: 'Netherlands Antilles',
        flagClass: 'fi-an',
        inputMasking: '999 9999',
        code: '+599 ',
        normalizedCode: '599',
    },
    {
        isoCode: 'AO',
        name: 'Angola',
        flagClass: 'fi-ao',
        inputMasking: '999 999 999',
        code: '+244 ',
        normalizedCode: '244',
    },
    {
        isoCode: 'AQ',
        name: 'Antarctica',
        flagClass: 'fi-aq',
        inputMasking: '9 99999',
        code: '+672 ',
        normalizedCode: '672',
    },
    {
        isoCode: 'AR',
        name: 'Argentina',
        flagClass: 'fi-ar',
        inputMasking: '999 99-9999-9999',
        code: '+54 ',
        normalizedCode: '54',
    },
    {
        isoCode: 'AS',
        name: 'American Samoa',
        flagClass: 'fi-as',
        inputMasking: '999-9999',
        code: '+1 (684) ',
        normalizedCode: '1684',
    },
    {
        isoCode: 'AT',
        name: 'Austria',
        flagClass: 'fi-at',
        inputMasking: '9999 999999',
        code: '+43 ',
        normalizedCode: '43',
    },
    {
        isoCode: 'AU',
        name: 'Australia',
        flagClass: 'fi-au',
        inputMasking: '9999 999 999',
        code: '+61 ',
        normalizedCode: '61',
    },
    {
        isoCode: 'AW',
        name: 'Aruba',
        flagClass: 'fi-aw',
        inputMasking: '999 9999',
        code: '+297 ',
        normalizedCode: '297',
    },
    {
        isoCode: 'AZ',
        name: 'Azerbaijan',
        flagClass: 'fi-az',
        inputMasking: '999 999 99 99',
        code: '+994 ',
        normalizedCode: '994',
    },
    {
        isoCode: 'BA',
        name: 'Bosnia and Herzegovina',
        flagClass: 'fi-ba',
        inputMasking: '999 999 999',
        code: '+387 ',
        normalizedCode: '387',
    },
    {
        isoCode: 'BB',
        name: 'Barbados',
        flagClass: 'fi-bb',
        inputMasking: '999-9999',
        code: '+1 (246) ',
        normalizedCode: '1246',
    },
    {
        isoCode: 'BD',
        name: 'Bangladesh',
        flagClass: 'fi-bd',
        inputMasking: '99999-999999',
        code: '+880 ',
        normalizedCode: '880',
    },
    {
        isoCode: 'BE',
        name: 'Belgium',
        flagClass: 'fi-be',
        inputMasking: '9999 99 99 99',
        code: '+32 ',
        normalizedCode: '32',
    },
    {
        isoCode: 'BF',
        name: 'Burkina Faso',
        flagClass: 'fi-bf',
        inputMasking: '99 99 99 99',
        code: '+226 ',
        normalizedCode: '226',
    },
    {
        isoCode: 'BG',
        name: 'Bulgaria',
        flagClass: 'fi-bg',
        inputMasking: '999 999 999',
        code: '+359 ',
        normalizedCode: '359',
    },
    {
        isoCode: 'BH',
        name: 'Bahrain',
        flagClass: 'fi-bh',
        inputMasking: '9999 9999',
        code: '+973 ',
        normalizedCode: '973',
    },
    {
        isoCode: 'BI',
        name: 'Burundi',
        flagClass: 'fi-bi',
        inputMasking: '99 99 99 99',
        code: '+257 ',
        normalizedCode: '257',
    },
    {
        isoCode: 'BJ',
        name: 'Benin',
        flagClass: 'fi-bj',
        inputMasking: '99 99 99 99',
        code: '+229 ',
        normalizedCode: '229',
    },
    {
        isoCode: 'BL',
        name: 'Saint Barthelemy',
        flagClass: 'fi-bl',
        inputMasking: '9999 99 99 99',
        code: '+590 ',
        normalizedCode: '590',
    },
    {
        isoCode: 'BM',
        name: 'Bermuda',
        flagClass: 'fi-bm',
        inputMasking: '999-9999',
        code: '+1 (441) ',
        normalizedCode: '1441',
    },
    {
        isoCode: 'BN',
        name: 'Brunei',
        flagClass: 'fi-bn',
        inputMasking: '999 9999',
        code: '+673 ',
        normalizedCode: '673',
    },
    {
        isoCode: 'BO',
        name: 'Bolivia',
        flagClass: 'fi-bo',
        inputMasking: '99999999',
        code: '+591 ',
        normalizedCode: '591',
    },
    {
        isoCode: 'BR',
        name: 'Brazil',
        flagClass: 'fi-br',
        inputMasking: '(99) 99999-9999',
        code: '+55 ',
        normalizedCode: '55',
    },
    {
        isoCode: 'BS',
        name: 'Bahamas',
        flagClass: 'fi-bs',
        inputMasking: '999-9999',
        code: '+1 (242) ',
        normalizedCode: '1242',
    },
    {
        isoCode: 'BT',
        name: 'Bhutan',
        flagClass: 'fi-bt',
        inputMasking: '99 99 99 99',
        code: '+975 ',
        normalizedCode: '975',
    },
    {
        isoCode: 'BW',
        name: 'Botswana',
        flagClass: 'fi-bw',
        inputMasking: '99 999 999',
        code: '+267 ',
        normalizedCode: '267',
    },
    {
        isoCode: 'BY',
        name: 'Belarus',
        flagClass: 'fi-by',
        inputMasking: '9 999 999-99-99',
        code: '+375 ',
        normalizedCode: '375',
    },
    {
        isoCode: 'BZ',
        name: 'Belize',
        flagClass: 'fi-bz',
        inputMasking: '999-9999',
        code: '+501 ',
        normalizedCode: '501',
    },
    {
        isoCode: 'CA',
        name: 'Canada',
        flagClass: 'fi-ca',
        inputMasking: '(999) 999-9999',
        code: '+1 ',
        normalizedCode: '1',
    },
    {
        isoCode: 'CC',
        name: 'Cocos Islands',
        flagClass: 'fi-cc',
        inputMasking: '9999 999 999',
        code: '+61 ',
        normalizedCode: '61',
    },
    {
        isoCode: 'CD',
        name: 'Democratic Republic of the Congo',
        flagClass: 'fi-cd',
        inputMasking: '9999 999 999',
        code: '+243 ',
        normalizedCode: '243',
    },
    {
        isoCode: 'CF',
        name: 'Central African Republic',
        flagClass: 'fi-cf',
        inputMasking: '99 99 99 99',
        code: '+236 ',
        normalizedCode: '236',
    },
    {
        isoCode: 'CG',
        name: 'Republic of the Congo',
        flagClass: 'fi-cg',
        inputMasking: ' 99 999 9999',
        code: '+242 ',
        normalizedCode: '242',
    },
    {
        isoCode: 'CH',
        name: 'Switzerland',
        flagClass: 'fi-ch',
        inputMasking: '999 999 99 99',
        code: '+41 ',
        normalizedCode: '41',
    },
    {
        isoCode: 'CI',
        name: 'Ivory Coast',
        flagClass: 'fi-ci',
        inputMasking: '99 99 99 99',
        code: '+225 ',
        normalizedCode: '225',
    },
    {
        isoCode: 'CK',
        name: 'Cook Islands',
        flagClass: 'fi-ck',
        inputMasking: '99 9999',
        code: '+682 ',
        normalizedCode: '682',
    },
    {
        isoCode: 'CL',
        name: 'Chile',
        flagClass: 'fi-cl',
        inputMasking: '9 9999 9999',
        code: '+56 ',
        normalizedCode: '56',
    },
    {
        isoCode: 'CM',
        name: 'Cameroon',
        flagClass: 'fi-cm',
        inputMasking: '9 99 99 99 99',
        code: '+237 ',
        normalizedCode: '237',
    },
    {
        isoCode: 'CN',
        name: 'China',
        flagClass: 'fi-cn',
        inputMasking: '999 9999 9999',
        code: '+86 ',
        normalizedCode: '86',
    },
    {
        isoCode: 'CO',
        name: 'Colombia',
        flagClass: 'fi-co',
        inputMasking: '999 9999999',
        code: '+57 ',
        normalizedCode: '57',
    },
    {
        isoCode: 'CR',
        name: 'Costa Rica',
        flagClass: 'fi-cr',
        inputMasking: '9999 9999',
        code: '+506 ',
        normalizedCode: '506',
    },
    {
        isoCode: 'CU',
        name: 'Cuba',
        flagClass: 'fi-cu',
        inputMasking: '99 9999999',
        code: '+53 ',
        normalizedCode: '53',
    },
    {
        isoCode: 'CV',
        name: 'Cape Verde',
        flagClass: 'fi-cv',
        inputMasking: '999 99 99',
        code: '+238 ',
        normalizedCode: '238',
    },
    {
        isoCode: 'CW',
        name: 'Curacao',
        flagClass: 'fi-cw',
        inputMasking: '999 9999',
        code: '+599 ',
        normalizedCode: '599',
    },
    {
        isoCode: 'CX',
        name: 'Christmas Island',
        flagClass: 'fi-cx',
        inputMasking: '9999 999 999',
        code: '+61 ',
        normalizedCode: '61',
    },
    {
        isoCode: 'CY',
        name: 'Cyprus',
        flagClass: 'fi-cy',
        inputMasking: '99 999999',
        code: '+357 ',
        normalizedCode: '357',
    },
    {
        isoCode: 'CZ',
        name: 'Czech Republic',
        flagClass: 'fi-cz',
        inputMasking: '999 999 999',
        code: '+420 ',
        normalizedCode: '420',
    },
    {
        isoCode: 'DE',
        name: 'Germany',
        flagClass: 'fi-de',
        inputMasking: '99999 9999999',
        code: '+49 ',
        normalizedCode: '49',
    },
    {
        isoCode: 'DJ',
        name: 'Djibouti',
        flagClass: 'fi-dj',
        inputMasking: '99 99 99 99',
        code: '+253 ',
        normalizedCode: '253',
    },
    {
        isoCode: 'DK',
        name: 'Denmark',
        flagClass: 'fi-dk',
        inputMasking: '99 99 99 99',
        code: '+45 ',
        normalizedCode: '45',
    },
    {
        isoCode: 'DM',
        name: 'Dominica',
        flagClass: 'fi-dm',
        inputMasking: '999-9999',
        code: '+1 (767) ',
        normalizedCode: '1767',
    },
    {
        isoCode: 'DO',
        name: 'Dominican Republic',
        flagClass: 'fi-do',
        inputMasking: '999-9999',
        code: '+1 (809) ',
        normalizedCode: '1809',
    },
    {
        isoCode: 'DZ',
        name: 'Algeria',
        flagClass: 'fi-dz',
        inputMasking: '9999 99 99 99',
        code: '+213 ',
        normalizedCode: '213',
    },
    {
        isoCode: 'EC',
        name: 'Ecuador',
        flagClass: 'fi-ec',
        inputMasking: '999 999 9999',
        code: '+593 ',
        normalizedCode: '593',
    },
    {
        isoCode: 'EE',
        name: 'Estonia',
        flagClass: 'fi-ee',
        inputMasking: '9999 9999',
        code: '+372 ',
        normalizedCode: '372',
    },
    {
        isoCode: 'EG',
        name: 'Egypt',
        flagClass: 'fi-eg',
        inputMasking: '9999 999 9999',
        code: '+20 ',
        normalizedCode: '20',
    },
    {
        isoCode: 'EH',
        name: 'Western Sahara',
        flagClass: 'fi-eh',
        inputMasking: '9999-999999',
        code: '+212 ',
        normalizedCode: '212',
    },
    {
        isoCode: 'ER',
        name: 'Eritrea',
        flagClass: 'fi-er',
        inputMasking: '99 999 999',
        code: '+291 ',
        normalizedCode: '291',
    },
    {
        isoCode: 'ES',
        name: 'Spain',
        flagClass: 'fi-es',
        inputMasking: '999 99 99 99',
        code: '+34 ',
        normalizedCode: '34',
    },
    {
        isoCode: 'ET',
        name: 'Ethiopia',
        flagClass: 'fi-et',
        inputMasking: '999 999 9999',
        code: '+251 ',
        normalizedCode: '251',
    },
    {
        isoCode: 'FI',
        name: 'Finland',
        flagClass: 'fi-fi',
        inputMasking: '999 9999999',
        code: '+358 ',
        normalizedCode: '358',
    },
    {
        isoCode: 'FJ',
        name: 'Fiji',
        flagClass: 'fi-fj',
        inputMasking: '999 9999',
        code: '+679 ',
        normalizedCode: '679',
    },
    {
        isoCode: 'FK',
        name: 'Falkland Islands',
        flagClass: 'fi-fk',
        inputMasking: '99999',
        code: '+500 ',
        normalizedCode: '500',
    },
    {
        isoCode: 'FM',
        name: 'Micronesia',
        flagClass: 'fi-fm',
        inputMasking: '999 9999',
        code: '+691 ',
        normalizedCode: '691',
    },
    {
        isoCode: 'FO',
        name: 'Faroe Islands',
        flagClass: 'fi-fo',
        inputMasking: '999999',
        code: '+298 ',
        normalizedCode: '298',
    },
    {
        isoCode: 'FR',
        name: 'France',
        flagClass: 'fi-fr',
        inputMasking: '99 99 99 99 99',
        code: '+33 ',
        normalizedCode: '33',
    },
    {
        isoCode: 'GA',
        name: 'Gabon',
        flagClass: 'fi-ga',
        inputMasking: '99 99 99 99',
        code: '+241 ',
        normalizedCode: '241',
    },
    {
        isoCode: 'GB',
        name: 'United Kingdom',
        flagClass: 'fi-gb',
        inputMasking: '99999 99999',
        code: '+44 ',
        normalizedCode: '44',
    },
    {
        isoCode: 'GD',
        name: 'Grenada',
        flagClass: 'fi-gd',
        inputMasking: '999-9999',
        code: '+1 (473) ',
        normalizedCode: '1473',
    },
    {
        isoCode: 'GE',
        name: 'Georgia',
        flagClass: 'fi-ge',
        inputMasking: '999 99 99 99',
        code: '+995 ',
        normalizedCode: '995',
    },
    {
        isoCode: 'GH',
        name: 'Ghana',
        flagClass: 'fi-gh',
        inputMasking: '999 999 9999',
        code: '+233 ',
        normalizedCode: '233',
    },
    {
        isoCode: 'GI',
        name: 'Gibraltar',
        flagClass: 'fi-gi',
        inputMasking: '99999999',
        code: '+350 ',
        normalizedCode: '350',
    },
    {
        isoCode: 'GL',
        name: 'Greenland',
        flagClass: 'fi-gl',
        inputMasking: '99 99 99',
        code: '+299 ',
        normalizedCode: '299',
    },
    {
        isoCode: 'GM',
        name: 'Gambia',
        flagClass: 'fi-gm',
        inputMasking: '999 9999',
        code: '+220 ',
        normalizedCode: '220',
    },
    {
        isoCode: 'GN',
        name: 'Guinea',
        flagClass: 'fi-gn',
        inputMasking: '999 99 99 99',
        code: '+224 ',
        normalizedCode: '224',
    },
    {
        isoCode: 'GQ',
        name: 'Equatorial Guinea',
        flagClass: 'fi-gq',
        inputMasking: '999 999 999',
        code: '+240 ',
        normalizedCode: '240',
    },
    {
        isoCode: 'GR',
        name: 'Greece',
        flagClass: 'fi-gr',
        inputMasking: '999 999 9999',
        code: '+30 ',
        normalizedCode: '30',
    },
    {
        isoCode: 'GT',
        name: 'Guatemala',
        flagClass: 'fi-gt',
        inputMasking: '9999 9999',
        code: '+502 ',
        normalizedCode: '502',
    },
    {
        isoCode: 'GU',
        name: 'Guam',
        flagClass: 'fi-gu',
        inputMasking: '999-9999',
        code: '+1 (671) ',
        normalizedCode: '1671',
    },
    {
        isoCode: 'GW',
        name: 'Guinea-Bissau',
        flagClass: 'fi-gw',
        inputMasking: '999 999 999',
        code: '+245 ',
        normalizedCode: '245',
    },
    {
        isoCode: 'GY',
        name: 'Guyana',
        flagClass: 'fi-gy',
        inputMasking: '999 9999',
        code: '+592 ',
        normalizedCode: '592',
    },
    {
        isoCode: 'HK',
        name: 'Hong Kong',
        flagClass: 'fi-hk',
        inputMasking: '9999 9999',
        code: '+852 ',
        normalizedCode: '852',
    },
    {
        isoCode: 'HN',
        name: 'Honduras',
        flagClass: 'fi-hn',
        inputMasking: '9999-9999',
        code: '+504 ',
        normalizedCode: '504',
    },
    {
        isoCode: 'HR',
        name: 'Croatia',
        flagClass: 'fi-hr',
        inputMasking: '999 999 9999',
        code: '+385 ',
        normalizedCode: '385',
    },
    {
        isoCode: 'HT',
        name: 'Haiti',
        flagClass: 'fi-ht',
        inputMasking: '99 99 9999',
        code: '+509 ',
        normalizedCode: '509',
    },
    {
        isoCode: 'HU',
        name: 'Hungary',
        flagClass: 'fi-hu',
        inputMasking: '(99) 999 9999',
        code: '+36 ',
        normalizedCode: '36',
    },
    {
        isoCode: 'ID',
        name: 'Indonesia',
        flagClass: 'fi-id',
        inputMasking: '9999-999-999',
        code: '+62 ',
        normalizedCode: '62',
    },
    {
        isoCode: 'IE',
        name: 'Ireland',
        flagClass: 'fi-ie',
        inputMasking: '999 999 9999',
        code: '+353 ',
        normalizedCode: '353',
    },
    {
        isoCode: 'IL',
        name: 'Israel',
        flagClass: 'fi-il',
        inputMasking: '999-999-9999',
        code: '+972 ',
        normalizedCode: '972',
    },
    {
        isoCode: 'IN',
        name: 'India',
        flagClass: 'fi-in',
        inputMasking: '99999 99999',
        code: '+91 ',
        normalizedCode: '91',
    },
    {
        isoCode: 'IO',
        name: 'British Indian Ocean Territory',
        flagClass: 'fi-io',
        inputMasking: '999 9999',
        code: '+246 ',
        normalizedCode: '246',
    },
    {
        isoCode: 'IQ',
        name: 'Iraq',
        flagClass: 'fi-iq',
        inputMasking: '9999 999 9999',
        code: '+964 ',
        normalizedCode: '964',
    },
    {
        isoCode: 'IR',
        name: 'Iran',
        flagClass: 'fi-ir',
        inputMasking: '9999 999 9999',
        code: '+98 ',
        normalizedCode: '98',
    },
    {
        isoCode: 'IS',
        name: 'Iceland',
        flagClass: 'fi-is',
        inputMasking: '999 9999',
        code: '+354 ',
        normalizedCode: '354',
    },
    {
        isoCode: 'IT',
        name: 'Italy',
        flagClass: 'fi-it',
        inputMasking: '999 999 9999',
        code: '+39 ',
        normalizedCode: '39',
    },
    {
        isoCode: 'JM',
        name: 'Jamaica',
        flagClass: 'fi-jm',
        inputMasking: '999-9999',
        code: '+1 (876) ',
        normalizedCode: '1876',
    },
    {
        isoCode: 'JO',
        name: 'Jordan',
        flagClass: 'fi-jo',
        inputMasking: '99 9999 9999',
        code: '+962 ',
        normalizedCode: '962',
    },
    {
        isoCode: 'JP',
        name: 'Japan',
        flagClass: 'fi-jp',
        inputMasking: '999 9999-9999',
        code: '+81 ',
        normalizedCode: '81',
    },
    {
        isoCode: 'KE',
        name: 'Kenya',
        flagClass: 'fi-ke',
        inputMasking: '9999 999999',
        code: '+254 ',
        normalizedCode: '254',
    },
    {
        isoCode: 'KG',
        name: 'Kyrgyzstan',
        flagClass: 'fi-kg',
        inputMasking: '9999 999 999',
        code: '+996 ',
        normalizedCode: '996',
    },
    {
        isoCode: 'KH',
        name: 'Cambodia',
        flagClass: 'fi-kh',
        inputMasking: '999 999 999',
        code: '+855 ',
        normalizedCode: '855',
    },
    {
        isoCode: 'KI',
        name: 'Kiribati',
        flagClass: 'fi-ki',
        inputMasking: '99999999',
        code: '+686 ',
        normalizedCode: '686',
    },
    {
        isoCode: 'KM',
        name: 'Comoros',
        flagClass: 'fi-km',
        inputMasking: '999 99 99',
        code: '+269 ',
        normalizedCode: '269',
    },
    {
        isoCode: 'KN',
        name: 'Saint Kitts and Nevis',
        flagClass: 'fi-kn',
        inputMasking: '999-9999',
        code: '+1 (869) ',
        normalizedCode: '1869',
    },
    {
        isoCode: 'KP',
        name: 'North Korea',
        flagClass: 'fi-kp',
        inputMasking: '9999 999 9999',
        code: '+850 ',
        normalizedCode: '850',
    },
    {
        isoCode: 'KR',
        name: 'South Korea',
        flagClass: 'fi-kr',
        inputMasking: '999-9999-9999',
        code: '+82 ',
        normalizedCode: '82',
    },
    {
        isoCode: 'KW',
        name: 'Kuwait',
        flagClass: 'fi-kw',
        inputMasking: '999 99999',
        code: '+965 ',
        normalizedCode: '965',
    },
    {
        isoCode: 'KY',
        name: 'Cayman Islands',
        flagClass: 'fi-ky',
        inputMasking: '999-9999',
        code: '+1 (345) ',
        normalizedCode: '1345',
    },
    {
        isoCode: 'KZ',
        name: 'Kazakhstan',
        flagClass: 'fi-kz',
        inputMasking: '9 (999) 999 9999',
        code: '+7 ',
        normalizedCode: '7',
    },
    {
        isoCode: 'LA',
        name: 'Laos',
        flagClass: 'fi-la',
        inputMasking: '999 99 999 999',
        code: '+856 ',
        normalizedCode: '856',
    },
    {
        isoCode: 'LB',
        name: 'Lebanon',
        flagClass: 'fi-lb',
        inputMasking: '99 999 999',
        code: '+961 ',
        normalizedCode: '961',
    },
    {
        isoCode: 'LC',
        name: 'Saint Lucia',
        flagClass: 'fi-lc',
        inputMasking: '999-9999',
        code: '+1 (758) ',
        normalizedCode: '1758',
    },
    {
        isoCode: 'LI',
        name: 'Liechtenstein',
        flagClass: 'fi-li',
        inputMasking: '999 999 999',
        code: '+423 ',
        normalizedCode: '423',
    },
    {
        isoCode: 'LK',
        name: 'Sri Lanka',
        flagClass: 'fi-lk',
        inputMasking: '999 999 9999',
        code: '+94 ',
        normalizedCode: '94',
    },
    {
        isoCode: 'LR',
        name: 'Liberia',
        flagClass: 'fi-lr',
        inputMasking: '999 999 9999',
        code: '+231 ',
        normalizedCode: '231',
    },
    {
        isoCode: 'LS',
        name: 'Lesotho',
        flagClass: 'fi-ls',
        inputMasking: '9999 9999',
        code: '+266 ',
        normalizedCode: '266',
    },
    {
        isoCode: 'LT',
        name: 'Lithuania',
        flagClass: 'fi-lt',
        inputMasking: '(9-999) 99999',
        code: '+370 ',
        normalizedCode: '370',
    },
    {
        isoCode: 'LU',
        name: 'Luxembourg',
        flagClass: 'fi-lu',
        inputMasking: '999 999 999',
        code: '+352 ',
        normalizedCode: '352',
    },
    {
        isoCode: 'LV',
        name: 'Latvia',
        flagClass: 'fi-lv',
        inputMasking: '99 999 999',
        code: '+371 ',
        normalizedCode: '371',
    },
    {
        isoCode: 'LY',
        name: 'Libya',
        flagClass: 'fi-ly',
        inputMasking: '999-9999999',
        code: '+218 ',
        normalizedCode: '218',
    },
    {
        isoCode: 'MA',
        name: 'Morocco',
        flagClass: 'fi-ma',
        inputMasking: '9999-999999',
        code: '+212 ',
        normalizedCode: '212',
    },
    {
        isoCode: 'MC',
        name: 'Monaco',
        flagClass: 'fi-mc',
        inputMasking: '99 99 99 99 99',
        code: '+377 ',
        normalizedCode: '377',
    },
    {
        isoCode: 'MD',
        name: 'Moldova',
        flagClass: 'fi-md',
        inputMasking: '9999 99 999',
        code: '+373 ',
        normalizedCode: '373',
    },
    {
        isoCode: 'ME',
        name: 'Montenegro',
        flagClass: 'fi-me',
        inputMasking: '999 999 999',
        code: '+382 ',
        normalizedCode: '382',
    },
    {
        isoCode: 'MF',
        name: 'Saint Martin',
        flagClass: 'fi-mf',
        inputMasking: '9999 99 99 99',
        code: '+590 ',
        normalizedCode: '590',
    },
    {
        isoCode: 'MG',
        name: 'Madagascar',
        flagClass: 'fi-mg',
        inputMasking: '999 99 999 99',
        code: '+261 ',
        normalizedCode: '261',
    },
    {
        isoCode: 'MH',
        name: 'Marshall Islands',
        flagClass: 'fi-mh',
        inputMasking: '999-9999',
        code: '+692 ',
        normalizedCode: '692',
    },
    {
        isoCode: 'MK',
        name: 'Macedonia',
        flagClass: 'fi-mk',
        inputMasking: '999 999 999',
        code: '+389 ',
        normalizedCode: '389',
    },
    {
        isoCode: 'ML',
        name: 'Mali',
        flagClass: 'fi-ml',
        inputMasking: '99 99 99 99',
        code: '+223 ',
        normalizedCode: '223',
    },
    {
        isoCode: 'MM',
        name: 'Myanmar',
        flagClass: 'fi-mm',
        inputMasking: '99 999 9999',
        code: '+95 ',
        normalizedCode: '95',
    },
    {
        isoCode: 'MN',
        name: 'Mongolia',
        flagClass: 'fi-mn',
        inputMasking: '9999 9999',
        code: '+976 ',
        normalizedCode: '976',
    },
    {
        isoCode: 'MO',
        name: 'Macau',
        flagClass: 'fi-mo',
        inputMasking: '9999 9999',
        code: '+853 ',
        normalizedCode: '853',
    },
    {
        isoCode: 'MP',
        name: 'Northern Mariana Islands',
        flagClass: 'fi-mp',
        inputMasking: '999-9999',
        code: '+1 (670) ',
        normalizedCode: '1670',
    },
    {
        isoCode: 'MR',
        name: 'Mauritania',
        flagClass: 'fi-mr',
        inputMasking: '99 99 99 99',
        code: '+222 ',
        normalizedCode: '222',
    },
    {
        isoCode: 'MS',
        name: 'Montserrat',
        flagClass: 'fi-ms',
        inputMasking: '999-9999',
        code: '+1 (664) ',
        normalizedCode: '1664',
    },
    {
        isoCode: 'MT',
        name: 'Malta',
        flagClass: 'fi-mt',
        inputMasking: '9999 9999',
        code: '+356 ',
        normalizedCode: '356',
    },
    {
        isoCode: 'MU',
        name: 'Mauritius',
        flagClass: 'fi-mu',
        inputMasking: '9999 9999',
        code: '+230 ',
        normalizedCode: '230',
    },
    {
        isoCode: 'MV',
        name: 'Maldives',
        flagClass: 'fi-mv',
        inputMasking: '999-9999',
        code: '+960 ',
        normalizedCode: '960',
    },
    {
        isoCode: 'MW',
        name: 'Malawi',
        flagClass: 'fi-mw',
        inputMasking: '9999 99 99 99',
        code: '+265 ',
        normalizedCode: '265',
    },
    {
        isoCode: 'MX',
        name: 'Mexico',
        flagClass: 'fi-mx',
        inputMasking: '999 999 999 9999',
        code: '+52 ',
        normalizedCode: '52',
    },
    {
        isoCode: 'MY',
        name: 'Malaysia',
        flagClass: 'fi-my',
        inputMasking: '999-999 9999',
        code: '+60 ',
        normalizedCode: '60',
    },
    {
        isoCode: 'MZ',
        name: 'Mozambique',
        flagClass: 'fi-mz',
        inputMasking: '99 999 9999',
        code: '+258 ',
        normalizedCode: '258',
    },
    {
        isoCode: 'NA',
        name: 'Namibia',
        flagClass: 'fi-na',
        inputMasking: '999 999 9999',
        code: '+264 ',
        normalizedCode: '264',
    },
    {
        isoCode: 'NC',
        name: 'New Caledonia',
        flagClass: 'fi-nc',
        inputMasking: '99 99 99',
        code: '+687 ',
        normalizedCode: '687',
    },
    {
        isoCode: 'NE',
        name: 'Niger',
        flagClass: 'fi-ne',
        inputMasking: '99 99 99 99',
        code: '+227 ',
        normalizedCode: '227',
    },
    {
        isoCode: 'NG',
        name: 'Nigeria',
        flagClass: 'fi-ng',
        inputMasking: '9999 999 9999',
        code: '+234 ',
        normalizedCode: '234',
    },
    {
        isoCode: 'NI',
        name: 'Nicaragua',
        flagClass: 'fi-ni',
        inputMasking: '9999 9999',
        code: '+505 ',
        normalizedCode: '505',
    },
    {
        isoCode: 'NL',
        name: 'Netherlands',
        flagClass: 'fi-nl',
        inputMasking: '99 99999999',
        code: '+31 ',
        normalizedCode: '31',
    },
    {
        isoCode: 'NO',
        name: 'Norway',
        flagClass: 'fi-no',
        inputMasking: '999 99 999',
        code: '+47 ',
        normalizedCode: '47',
    },
    {
        isoCode: 'NP',
        name: 'Nepal',
        flagClass: 'fi-np',
        inputMasking: '999-9999999',
        code: '+977 ',
        normalizedCode: '977',
    },
    {
        isoCode: 'NR',
        name: 'Nauru',
        flagClass: 'fi-nr',
        inputMasking: '999 9999',
        code: '+674 ',
        normalizedCode: '674',
    },
    {
        isoCode: 'NU',
        name: 'Niue',
        flagClass: 'fi-nu',
        inputMasking: '999 9999',
        code: '+683 ',
        normalizedCode: '683',
    },
    {
        isoCode: 'NZ',
        name: 'New Zealand',
        flagClass: 'fi-nz',
        inputMasking: '999 999 9999',
        code: '+64 ',
        normalizedCode: '64',
    },
    {
        isoCode: 'OM',
        name: 'Oman',
        flagClass: 'fi-om',
        inputMasking: '9999 9999',
        code: '+968 ',
        normalizedCode: '968',
    },
    {
        isoCode: 'PA',
        name: 'Panama',
        flagClass: 'fi-pa',
        inputMasking: '9999-9999',
        code: '+507 ',
        normalizedCode: '507',
    },
    {
        isoCode: 'PE',
        name: 'Peru',
        flagClass: 'fi-pe',
        inputMasking: '999 999 999',
        code: '+51 ',
        normalizedCode: '51',
    },
    {
        isoCode: 'PF',
        name: 'French Polynesia',
        flagClass: 'fi-pf',
        inputMasking: '99 99 99 99',
        code: '+689 ',
        normalizedCode: '689',
    },
    {
        isoCode: 'PG',
        name: 'Papua New Guinea',
        flagClass: 'fi-pg',
        inputMasking: '9999 9999',
        code: '+675 ',
        normalizedCode: '675',
    },
    {
        isoCode: 'PH',
        name: 'Philippines',
        flagClass: 'fi-ph',
        inputMasking: '9999 999 9999',
        code: '+63 ',
        normalizedCode: '63',
    },
    {
        isoCode: 'PK',
        name: 'Pakistan',
        flagClass: 'fi-pk',
        inputMasking: '9999 9999999',
        code: '+92 ',
        normalizedCode: '92',
    },
    {
        isoCode: 'PL',
        name: 'Poland',
        flagClass: 'fi-pl',
        inputMasking: '999 999 999',
        code: '+48 ',
        normalizedCode: '48',
    },
    {
        isoCode: 'PM',
        name: 'Saint Pierre and Miquelon',
        flagClass: 'fi-pm',
        inputMasking: '999 99 99',
        code: '+508 ',
        normalizedCode: '508',
    },
    {
        isoCode: 'PN',
        name: 'Pitcairn',
        flagClass: 'fi-pn',
        inputMasking: '99 999999',
        code: '+64 ',
        normalizedCode: '64',
    },
    {
        isoCode: 'PR',
        name: 'Puerto Rico',
        flagClass: 'fi-pr',
        inputMasking: '999-9999',
        code: '+1 (787) ',
        normalizedCode: '1787',
    },
    {
        isoCode: 'PS',
        name: 'Palestine',
        flagClass: 'fi-ps',
        inputMasking: '9999 999 999',
        code: '+970 ',
        normalizedCode: '970',
    },
    {
        isoCode: 'PT',
        name: 'Portugal',
        flagClass: 'fi-pt',
        inputMasking: '999 999 999',
        code: '+351 ',
        normalizedCode: '351',
    },
    {
        isoCode: 'PW',
        name: 'Palau',
        flagClass: 'fi-pw',
        inputMasking: '999 9999',
        code: '+680 ',
        normalizedCode: '680',
    },
    {
        isoCode: 'PY',
        name: 'Paraguay',
        flagClass: 'fi-py',
        inputMasking: '9999 999999',
        code: '+595 ',
        normalizedCode: '595',
    },
    {
        isoCode: 'QA',
        name: 'Qatar',
        flagClass: 'fi-qa',
        inputMasking: '9999 9999',
        code: '+974 ',
        normalizedCode: '974',
    },
    {
        isoCode: 'RE',
        name: 'Reunion',
        flagClass: 'fi-re',
        inputMasking: '9999 99 99 99',
        code: '+262 ',
        normalizedCode: '262',
    },
    {
        isoCode: 'RO',
        name: 'Romania',
        flagClass: 'fi-ro',
        inputMasking: '9999 999 999',
        code: '+40 ',
        normalizedCode: '40',
    },
    {
        isoCode: 'RS',
        name: 'Serbia',
        flagClass: 'fi-rs',
        inputMasking: '999 9999999',
        code: '+381 ',
        normalizedCode: '381',
    },
    {
        isoCode: 'RU',
        name: 'Russia',
        flagClass: 'fi-ru',
        inputMasking: '9 (999) 999-99-99',
        code: '+7 ',
        normalizedCode: '7',
    },
    {
        isoCode: 'RW',
        name: 'Rwanda',
        flagClass: 'fi-rw',
        inputMasking: '9999 999 999',
        code: '+250 ',
        normalizedCode: '250',
    },
    {
        isoCode: 'SA',
        name: 'Saudi Arabia',
        flagClass: 'fi-sa',
        inputMasking: '999 999 9999',
        code: '+966 ',
        normalizedCode: '966',
    },
    {
        isoCode: 'SB',
        name: 'Solomon Islands',
        flagClass: 'fi-sb',
        inputMasking: '99 99999',
        code: '+677 ',
        normalizedCode: '677',
    },
    {
        isoCode: 'SC',
        name: 'Seychelles',
        flagClass: 'fi-sc',
        inputMasking: '9 999 999',
        code: '+248 ',
        normalizedCode: '248',
    },
    {
        isoCode: 'SD',
        name: 'Sudan',
        flagClass: 'fi-sd',
        inputMasking: '999 999 9999',
        code: '+249 ',
        normalizedCode: '249',
    },
    {
        isoCode: 'SE',
        name: 'Sweden',
        flagClass: 'fi-se',
        inputMasking: '999-999 99 99',
        code: '+46 ',
        normalizedCode: '46',
    },
    {
        isoCode: 'SG',
        name: 'Singapore',
        flagClass: 'fi-sg',
        inputMasking: '9999 9999',
        code: '+65 ',
        normalizedCode: '65',
    },
    {
        isoCode: 'SH',
        name: 'Saint Helena',
        flagClass: 'fi-sh',
        inputMasking: '99999',
        code: '+290 ',
        normalizedCode: '290',
    },
    {
        isoCode: 'SI',
        name: 'Slovenia',
        flagClass: 'fi-si',
        inputMasking: '999 999 999',
        code: '+386 ',
        normalizedCode: '386',
    },
    {
        isoCode: 'SJ',
        name: 'Svalbard and Jan Mayen',
        flagClass: 'fi-sj',
        inputMasking: '999 99 999',
        code: '+47 ',
        normalizedCode: '47',
    },
    {
        isoCode: 'SK',
        name: 'Slovakia',
        flagClass: 'fi-sk',
        inputMasking: '9999 999 999',
        code: '+421 ',
        normalizedCode: '421',
    },
    {
        isoCode: 'SL',
        name: 'Sierra Leone',
        flagClass: 'fi-sl',
        inputMasking: '(999) 999999',
        code: '+232 ',
        normalizedCode: '232',
    },
    {
        isoCode: 'SM',
        name: 'San Marino',
        flagClass: 'fi-sm',
        inputMasking: '99 99 99 99',
        code: '+378 ',
        normalizedCode: '378',
    },
    {
        isoCode: 'SN',
        name: 'Senegal',
        flagClass: 'fi-sn',
        inputMasking: '99 999 99 99',
        code: '+221 ',
        normalizedCode: '221',
    },
    {
        isoCode: 'SO',
        name: 'Somalia',
        flagClass: 'fi-so',
        inputMasking: '9 9999999',
        code: '+252 ',
        normalizedCode: '252',
    },
    {
        isoCode: 'SR',
        name: 'Suriname',
        flagClass: 'fi-sr',
        inputMasking: '999-9999',
        code: '+597 ',
        normalizedCode: '597',
    },
    {
        isoCode: 'SS',
        name: 'South Sudan',
        flagClass: 'fi-ss',
        inputMasking: '9999 999 999',
        code: '+211 ',
        normalizedCode: '211',
    },
    {
        isoCode: 'ST',
        name: 'Sao Tome and Principe',
        flagClass: 'fi-st',
        inputMasking: '999 9999',
        code: '+239 ',
        normalizedCode: '239',
    },
    {
        isoCode: 'SV',
        name: 'El Salvador',
        flagClass: 'fi-sv',
        inputMasking: '9999 9999',
        code: '+503 ',
        normalizedCode: '503',
    },
    {
        isoCode: 'SX',
        name: 'Sint Maarten',
        flagClass: 'fi-sx',
        inputMasking: '999-9999',
        code: '+1 (721) ',
        normalizedCode: '1721',
    },
    {
        isoCode: 'SY',
        name: 'Syria',
        flagClass: 'fi-sy',
        inputMasking: '9999 999 999',
        code: '+963 ',
        normalizedCode: '963',
    },
    {
        isoCode: 'SZ',
        name: 'Swaziland',
        flagClass: 'fi-sz',
        inputMasking: '9999 9999',
        code: '+268 ',
        normalizedCode: '268',
    },
    {
        isoCode: 'TC',
        name: 'Turks and Caicos Islands',
        flagClass: 'fi-tc',
        inputMasking: '999-9999',
        code: '+1 (649) ',
        normalizedCode: '1649',
    },
    {
        isoCode: 'TD',
        name: 'Chad',
        flagClass: 'fi-td',
        inputMasking: '99 99 99 99',
        code: '+235 ',
        normalizedCode: '235',
    },
    {
        isoCode: 'TG',
        name: 'Togo',
        flagClass: 'fi-tg',
        inputMasking: '99 99 99 99',
        code: '+228 ',
        normalizedCode: '228',
    },
    {
        isoCode: 'TH',
        name: 'Thailand',
        flagClass: 'fi-th',
        inputMasking: '999 999 9999',
        code: '+66 ',
        normalizedCode: '66',
    },
    {
        isoCode: 'TJ',
        name: 'Tajikistan',
        flagClass: 'fi-tj',
        inputMasking: '999 99 9999',
        code: '+992 ',
        normalizedCode: '992',
    },
    {
        isoCode: 'TK',
        name: 'Tokelau',
        flagClass: 'fi-tk',
        inputMasking: '9999',
        code: '+690 ',
        normalizedCode: '690',
    },
    {
        isoCode: 'TL',
        name: 'East Timor',
        flagClass: 'fi-tl',
        inputMasking: '9999 9999',
        code: '+670 ',
        normalizedCode: '670',
    },
    {
        isoCode: 'TM',
        name: 'Turkmenistan',
        flagClass: 'fi-tm',
        inputMasking: '9 99 999999',
        code: '+993 ',
        normalizedCode: '993',
    },
    {
        isoCode: 'TN',
        name: 'Tunisia',
        flagClass: 'fi-tn',
        inputMasking: '99 999 999',
        code: '+216 ',
        normalizedCode: '216',
    },
    {
        isoCode: 'TO',
        name: 'Tonga',
        flagClass: 'fi-to',
        inputMasking: '999 9999',
        code: '+676 ',
        normalizedCode: '676',
    },
    {
        isoCode: 'TR',
        name: 'Turkey',
        flagClass: 'fi-tr',
        inputMasking: '9999 999 99 99',
        code: '+90 ',
        normalizedCode: '90',
    },
    {
        isoCode: 'TT',
        name: 'Trinidad and Tobago',
        flagClass: 'fi-tt',
        inputMasking: '999-9999',
        code: '+1 (868) ',
        normalizedCode: '1868',
    },
    {
        isoCode: 'TV',
        name: 'Tuvalu',
        flagClass: 'fi-tv',
        inputMasking: '999999',
        code: '+688 ',
        normalizedCode: '688',
    },
    {
        isoCode: 'TW',
        name: 'Taiwan',
        flagClass: 'fi-tw',
        inputMasking: '9999 999 999',
        code: '+886 ',
        normalizedCode: '886',
    },
    {
        isoCode: 'TZ',
        name: 'Tanzania',
        flagClass: 'fi-tz',
        inputMasking: '9999 999 999',
        code: '+255 ',
        normalizedCode: '255',
    },
    {
        isoCode: 'UA',
        name: 'Ukraine',
        flagClass: 'fi-ua',
        inputMasking: '999 999 9999',
        code: '+380 ',
        normalizedCode: '380',
    },
    {
        isoCode: 'UG',
        name: 'Uganda',
        flagClass: 'fi-ug',
        inputMasking: '9999 999999',
        code: '+256 ',
        normalizedCode: '256',
    },
    {
        isoCode: 'US',
        name: 'United States',
        flagClass: 'fi-us',
        inputMasking: '(999) 999-9999',
        code: '+1 ',
        normalizedCode: '1',
    },
    {
        isoCode: 'UY',
        name: 'Uruguay',
        flagClass: 'fi-uy',
        inputMasking: '999 999 999',
        code: '+598 ',
        normalizedCode: '598',
    },
    {
        isoCode: 'UZ',
        name: 'Uzbekistan',
        flagClass: 'fi-uz',
        inputMasking: '9 99 999 99 99',
        code: '+998 ',
        normalizedCode: '998',
    },
    {
        isoCode: 'VA',
        name: 'Vatican',
        flagClass: 'fi-va',
        inputMasking: '999 999 9999',
        code: '+39 ',
        normalizedCode: '39',
    },
    {
        isoCode: 'VC',
        name: 'Saint Vincent and the Grenadines',
        flagClass: 'fi-vc',
        inputMasking: '999-9999',
        code: '+1 (784) ',
        normalizedCode: '1784',
    },
    {
        isoCode: 'VE',
        name: 'Venezuela',
        flagClass: 'fi-ve',
        inputMasking: '9999-9999999',
        code: '+58 ',
        normalizedCode: '58',
    },
    {
        isoCode: 'VG',
        name: 'British Virgin Islands',
        flagClass: 'fi-vg',
        inputMasking: '999-9999',
        code: '+1 (284) ',
        normalizedCode: '1284',
    },
    {
        isoCode: 'VI',
        name: 'U.S. Virgin Islands',
        flagClass: 'fi-vi',
        inputMasking: '999-9999',
        code: '+1 (340) ',
        normalizedCode: '1340',
    },
    {
        isoCode: 'VN',
        name: 'Vietnam',
        flagClass: 'fi-vn',
        inputMasking: '999 999 99 99',
        code: '+84 ',
        normalizedCode: '84',
    },
    {
        isoCode: 'VU',
        name: 'Vanuatu',
        flagClass: 'fi-vu',
        inputMasking: '999 9999',
        code: '+678 ',
        normalizedCode: '678',
    },
    {
        isoCode: 'WF',
        name: 'Wallis and Futuna',
        flagClass: 'fi-wf',
        inputMasking: '99 99 99',
        code: '+681 ',
        normalizedCode: '681',
    },
    {
        isoCode: 'WS',
        name: 'Samoa',
        flagClass: 'fi-ws',
        inputMasking: '99 99999',
        code: '+685 ',
        normalizedCode: '685',
    },
    {
        isoCode: 'XK',
        name: 'Kosovo',
        flagClass: 'fi-xk',
        inputMasking: '999 999 999',
        code: '+383 ',
        normalizedCode: '383',
    },
    {
        isoCode: 'YE',
        name: 'Yemen',
        flagClass: 'fi-ye',
        inputMasking: '9999 999 999',
        code: '+967 ',
        normalizedCode: '967',
    },
    {
        isoCode: 'YT',
        name: 'Mayotte',
        flagClass: 'fi-yt',
        inputMasking: '9999 99 99 99',
        code: '+262 ',
        normalizedCode: '262',
    },
    {
        isoCode: 'ZA',
        name: 'South Africa',
        flagClass: 'fi-za',
        inputMasking: '999 999 9999',
        code: '+27 ',
        normalizedCode: '27',
    },
    {
        isoCode: 'ZM',
        name: 'Zambia',
        flagClass: 'fi-zm',
        inputMasking: '999 9999999',
        code: '+260 ',
        normalizedCode: '260',
    },
    {
        isoCode: 'ZW',
        name: 'Zimbabwe',
        flagClass: 'fi-zw',
        inputMasking: '999 999 9999',
        code: '+263 ',
        normalizedCode: '263',
    },
];
